#Feature Engineering : Standardization and Scaling
 # Date: 02-09-2022



In [7]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [4]:
a = np.random.randint(10, size=(10,1))
b = np.random.randint(50, 100, size=(10,1))
c = np.random.randint(500, 700, size=(10,1))
X = np.concatenate((a,b,c), axis=1)
X

array([[  5,  57, 614],
       [  6,  82, 663],
       [  0,  80, 525],
       [  9,  60, 629],
       [  9,  98, 567],
       [  6,  90, 582],
       [  7,  71, 568],
       [  0,  92, 666],
       [  8,  95, 577],
       [  0,  72, 589]])

# Mean and Std before Scaling

In [5]:
X.mean(axis=0)

array([  5. ,  79.7, 598. ])

In [6]:
X.std(axis=0)

array([ 3.49284984, 13.67515996, 42.46645735])

# Mean and STD after standrdization

In [8]:
sc = preprocessing.StandardScaler().fit(X)

In [9]:
X_standardized = sc.transform(X)

In [10]:
X_standardized.mean(axis=0)

array([-2.22044605e-17, -2.22044605e-16,  1.38777878e-17])

In [11]:
X_standardized.std(axis=0)

array([1., 1., 1.])